POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer 

{
    "title":"new thingy",
    "author":"someone someone",
    "url":"www.blog123.com",
    "likes":2,
    "user":"6675d18ca135ca65fc3505d0"
}
