POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title":"new blog",
    "author":"blogger",
    "url":"www.blog.com",
    "likes":12323,
    "user":"6675d18ca135ca65fc3505d0"
}
